import type { Achievement, TweaksConfig } from "@/types";

export const ANIME_CLASSES: { en: string; jp: string; threshold: Record<string, number> }[] = [
  { en: "Dreamer Class", jp: "幻想型", threshold: { fantasy: 60, romance: 40 } },
  { en: "Warrior Class", jp: "戦闘型", threshold: { action: 70 } },
  { en: "Philosopher Class", jp: "哲学型", threshold: { psychological: 65 } },
  { en: "Empath Class", jp: "感情型", threshold: { drama: 60, romance: 50 } },
  { en: "Slice-of-Life Enjoyer", jp: "日常型", threshold: { sliceOfLife: 65 } },
  { en: "Comedy Connoisseur", jp: "笑劇型", threshold: { comedy: 65 } },
  { en: "All-Rounder", jp: "万能型", threshold: {} },
];

export const TRIGGER_TAGS = [
  "Mentor death",
  "Rival speech",
  "Confession scene",
  "Final battle",
  "Quiet monologue",
  "Festival episode",
  "Sacrifice moment",
  "Reunion scene",
  "Training arc",
  "Plot twist",
  "Found family moment",
  "Farewell scene",
  "Power-up reveal",
  "Villain's backstory",
  "Last episode",
];

export const ACHIEVEMENTS_DEFINITIONS: Achievement[] = [
  {
    id: "ep19-survivor",
    title: "Episode 19 Survivor",
    titleJP: "第19話サバイバー",
    description: "Survived the most brutal episode 19 ever written.",
    icon: "🔥",
    unlocked: false,
    category: "emotional",
  },
  {
    id: "binge-master",
    title: "12-Episode Binge Master",
    titleJP: "一気見マスター",
    description: "Watched an entire cour in a single sitting.",
    icon: "⚡",
    unlocked: false,
    category: "binge",
  },
  {
    id: "slice-enjoyer",
    title: "Slice-of-Life Enjoyer",
    titleJP: "日常系愛好家",
    description: "Completed 5 slice-of-life series.",
    icon: "🍵",
    unlocked: false,
    category: "variety",
  },
  {
    id: "philosophy-enjoyer",
    title: "Philosophy Enthusiast",
    titleJP: "哲学的探求者",
    description: "Watched 3 psychological / philosophical anime.",
    icon: "🌀",
    unlocked: false,
    category: "variety",
  },
  {
    id: "100-episodes",
    title: "Century Viewer",
    titleJP: "百話突破",
    description: "Crossed 100 total episodes watched.",
    icon: "💯",
    unlocked: false,
    category: "dedication",
  },
  {
    id: "10-completed",
    title: "Veteran Viewer",
    titleJP: "十作完走",
    description: "Completed 10 anime series.",
    icon: "🏅",
    unlocked: false,
    category: "dedication",
  },
  {
    id: "emotional-wreck",
    title: "Emotional Wreck",
    titleJP: "感情崩壊",
    description: "Cried during at least 3 different shows.",
    icon: "😭",
    unlocked: false,
    category: "emotional",
  },
  {
    id: "year-veteran",
    title: "Year One Veteran",
    titleJP: "一年生き残り",
    description: "Been watching anime for over a year.",
    icon: "📅",
    unlocked: false,
    category: "dedication",
  },
];

export const DEFAULT_TWEAKS: TweaksConfig = {
  theme: "cream",
  brightness: 1,
  borderStyle: "sketchy",
  language: "both",
  density: "spacious",
};

export const THEME_PRESETS = {
  cream: {
    label: "Cream",
    labelJP: "クリーム",
    emoji: "🍞",
    bg: "#F5F0E8",
    card: "#FFFDF7",
    text: "#292524",
    accent: "#B91C1C",
    accentAlt: "#F59E0B",
  },
  dark: {
    label: "Dark",
    labelJP: "ダーク",
    emoji: "🌑",
    bg: "#1C1917",
    card: "#292524",
    text: "#F5F0E8",
    accent: "#EF4444",
    accentAlt: "#F59E0B",
  },
  sakura: {
    label: "Sakura",
    labelJP: "桜",
    emoji: "🌸",
    bg: "#FDF2F8",
    card: "#FFF5FB",
    text: "#831843",
    accent: "#DB2777",
    accentAlt: "#F472B6",
  },
  ocean: {
    label: "Ocean",
    labelJP: "海",
    emoji: "🌊",
    bg: "#EFF6FF",
    card: "#F8FBFF",
    text: "#1E3A5F",
    accent: "#1D4ED8",
    accentAlt: "#0EA5E9",
  },
  matcha: {
    label: "Matcha",
    labelJP: "抹茶",
    emoji: "🍵",
    bg: "#F0FDF4",
    card: "#F7FFF9",
    text: "#14532D",
    accent: "#16A34A",
    accentAlt: "#65A30D",
  },
} as const;
